version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5136:8080"  # Mapea el puerto 5136 en tu máquina al puerto 8080 del contenedor (backend)
    environment:
      - ASPNETCORE_URLS=http://+:8080  # El backend escucha en el puerto 8080 dentro del contenedor
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # El frontend sigue en el puerto 3000 en tu máquina
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
